import { ArcManagedSDK } from '../arc-sdk/src/ArcManagedSDK.js';
import { id } from 'ethers';
import * as fs from 'fs';

async function main() {
    const taskId = process.argv[2];
    if (!taskId) {
        console.error("Usage: node scripts/submit_work.js <taskId>");
        process.exit(1);
    }
    console.log(`🦅 Saske: Submitting Work for Task #${taskId}...`);
    const sdk = new ArcManagedSDK();

    const reportContent = "Intelligence report for Task #" + taskId + " - Content generated by Saske.";
    const resultHash = id(reportContent);
    const resultURI = "https://gist.github.com/saske/task-report-" + taskId; 

    try {
        const res = await sdk.submitResult({
            taskId: taskId,
            resultHash: resultHash,
            resultURI: resultURI
        });

        if (res.success) {
            console.log(`✅ SUCCESS! Work submitted for Task #${taskId}.`);
            console.log(">> Result Hash:", resultHash);
        } else {
            console.error("!! Submission failed:", res.error);
        }
    } catch (err) {
        console.error("!! Error:", err.response ? JSON.stringify(err.response.data) : err.message);
    }
}

main();
